# Generated by Django 3.2.3 on 2023-10-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20231031_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagforrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_for_recipe', to='foods.recipe'),
        ),
    ]
