# Generated by Django 3.2.3 on 2023-11-01 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20231031_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='ingredientforrecipe',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tagforrecipe',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Cooking_time должно быть больше 1'), django.core.validators.MaxValueValidator(10000, 'Да что вы там такое готовите?')]),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
    ]
