# Generated by Django 3.2.3 on 2023-11-01 22:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20231102_0058'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='forbidden_self_subscription',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('author')), _negated=True), name='forbidden_self_subscription'),
        ),
    ]
